openapi: 3.1.0
info:
  title: Parameters API
  version: 1.0.0

components:
  schemas:
    Parameter:
      type: object
      description: A configurable parameter
      required:
        - key
        - value
        - type
        - description
      properties:
        key:
          type: string
          description: Unique name of the parameter
        value:
          type: string
          description: Current value of the parameter
        type:
          type: string
          description: Data type of the parameter (e.g., string, integer, boolean)
        description:
          type: string
          description: Human readable description of the parameter

    ParameterUpdateRequest:
      type: object
      description: Payload for updating a parameter
      required:
        - key
        - value
      properties:
        key:
          type: string
          description: Name of the parameter to update
        value:
          type: string
          description: New value to assign

    ErrorResponse:
      type: object
      description: Error response
      properties:
        error:
          type: string
          description: Error message
    Order:
      type: object
      description: An order object for a trade.
      required:
        - id
        - symbol
        - size
        - price
        - timestamp
        - exchange
        - side
        - status
      properties:
        id:
          type: string
          description: Unique identifier for the order
        symbol:
          type: string
          description: Trading symbol (e.g., BTCUSD)
        size:
          type: number
          description: Size of the order
        price:
          type: number
          description: Price at which the order was placed
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the order was created
        exchange:
          type: string
          description: Exchange where the order was placed
        side:
          type: string
          description: Side of the order (buy/sell)
        status:
          type: string
          description: Current status of the order (e.g., open, closed, canceled)

paths:
  /orders:
    get:
      summary: Get all orders
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                description: Array of all orders
                items:
                  $ref: '#/components/schemas/Order'
  /parameters:
    get:
      summary: Get all parameters
      responses:
        '200':
          description: List of parameters
          content:
            application/json:
              schema:
                type: array
                description: Array of all available parameters
                items:
                  $ref: '#/components/schemas/Parameter'

    post:
      summary: Update a parameter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParameterUpdateRequest'
      responses:
        '200':
          description: Parameter updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parameter'
        '404':
          description: Parameter not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
